### PR TITLE
Update codeql-analysis.yml

### PR DESCRIPTION
**Pull request by mikk5829**
Trying to run actions on self hosted runner

### CODE REVIEW

**Comment by tbdk** [comment]
Closing while sorting out some runner issues, then re-opening.

**Comment by mikk5829** [comment]
@tbdk Can u have a look again?

**Review by tbdk — APPROVED** [review]
lgtm :rocket:

**Comment by tbdk** [comment]
Approved, but I also now just realized, that there might not be any incentive to be running it on the self hosted runner? :slightly_smiling_face: But you can merge if you'd like it to :-)

**Comment by afskylia** [comment]
@mikk5829 må denne merges??

**Pull request closed without merging**
